interface Character {
    id: number;
    ipa: string;
    latinSymbol: string;
    englishApproximation: string;
    video: string;
    vowel: boolean;
    variants: {
        isolated: string;
        final: string;
        medial: string;
        initial: string;
    }
}

interface Word {
    id: number;
    sorani: string;
    english: string;
    ipa: string;
}

export const alphabet: Character[] = [
    {
        id: 1,
        ipa: '[aː]',
        latinSymbol: 'a',
        englishApproximation: '<p>f<strong>a</strong>ther</p>',
        video: 'https://www.youtube.com/watch?v=7FEaBhuM4b0&t=7s',
        vowel: true,
        variants: {
            isolated: 'ا',
            final: 'ـا',
            medial: 'ـا',
            initial: '—',
        },
    },
    {
        id: 2,
        ipa: '[b]',
        latinSymbol: 'b',
        englishApproximation: '<p><strong>b</strong>oy</p>',
        video: 'https://www.youtube.com/watch?v=W5nBRnlctwY&t=7s',
        vowel: false,
        variants: {
            isolated: 'ب',
            final: 'ـب',
            medial: 'ـبـ',
            initial: 'بـ',
        },
    },
    {
        id: 3,
        ipa: '[d͡ʒ]',
        latinSymbol: 'c',
        englishApproximation: '<p><strong>j</strong>uice</p>',
        video: 'https://www.youtube.com/watch?v=zZRSSXMurro&t=7s',
        vowel: false,
        variants: {
            isolated: 'ج',
            final: 'ـج',
            medial: 'ـجـ',
            initial: 'جـ',
        },
    },
    {
        id: 4,
        ipa: '[t͡ʃ]',
        latinSymbol: 'ç',
        englishApproximation: '<p><strong>ch</strong>est</p>',
        video: 'https://www.youtube.com/watch?v=J5RYdw_0CL0&t=7s',
        vowel: false,
        variants: {
            isolated: 'چ',
            final: 'ـچ',
            medial: 'ـچـ',
            initial: 'چـ',
        },
    },
    {
        id: 5,
        ipa: '[d]',
        latinSymbol: 'd',
        englishApproximation: '<p><strong>d</strong>og</p>',
        video: 'https://www.youtube.com/watch?v=dwKWvT50_o0&t=7s',
        vowel: false,
        variants: {
            isolated: 'د',
            final: 'ـد‎',
            medial: 'ـد‎',
            initial: 'د‎',
        },
    },
    {
        id: 6,
        ipa: '[ɛ]',
        latinSymbol: 'e',
        englishApproximation: '<p>b<strong>e</strong>d</p>',
        video: 'https://www.youtube.com/watch?v=fy4Br68Urwg&t=7s',
        vowel: true,
        variants: {
            isolated: 'ە',
            final: 'ـە',
            medial: 'ـە',
            initial: 'ە',
        },
    },
    {
        id: 7,
        ipa: '[eː]',
        latinSymbol: 'ê',
        englishApproximation: '<p>p<strong>ay</strong></p>',
        video: 'https://www.youtube.com/watch?v=Rf7juiYd8lM&t=7s',
        vowel: true,
        variants: {
            isolated: 'ێ',
            final: 'ـێ',
            medial: 'ـێـ',
            initial: 'ێـ',
        },
    },
    {
        id: 8,
        ipa: '[f]',
        latinSymbol: 'f',
        englishApproximation: '<p><strong>f</strong>oot</p>',
        video: 'https://www.youtube.com/watch?v=MYhNt-MgJ-c&t=7s',
        vowel: false,
        variants: {
            isolated: 'ف',
            final: 'ـف',
            medial: 'ـفـ',
            initial: 'فـ',
        },
    },
    {
        id: 9,
        ipa: '[ɡ]',
        latinSymbol: 'g',
        englishApproximation: '<p><strong>g</strong>ood</p>',
        video: 'https://www.youtube.com/watch?v=5YiAj9mLE_4&t=7s',
        vowel: false,
        variants: {
            isolated: 'گ',
            final: 'ـگ',
            medial: 'ـگـ',
            initial: 'گـ',
        },
    },
    {
        id: 10,
        ipa: '[h]',
        latinSymbol: 'h',
        englishApproximation: '<p><strong>h</strong>ope</p>',
        video: 'https://www.youtube.com/watch?v=Y3UnCmcaJOQ&t=7s',
        vowel: false,
        variants: {
            isolated: 'ھ',
            final: '—',
            medial: 'ـھـ',
            initial: 'ھ',
        },
    },
    {
        id: 11,
        ipa: '[ħ]',
        latinSymbol: 'ḧ',
        englishApproximation: '<p>somewhat like <strong>h</strong>ope</p>',
        video: 'https://www.youtube.com/watch?v=RbVnTjuFixE&t=7s',
        vowel: false,
        variants: {
            isolated: 'ح',
            final: 'ـح',
            medial: 'ـحـ‎',
            initial: 'حـ',
        },
    },
    {
        id: 12,
        ipa: '[ɨ]',
        latinSymbol: 'i',
        englishApproximation: '<p>s<strong>i</strong>t</p>',
        video: '#',
        vowel: true,
        variants: {
            isolated: '—',
            final: '—',
            medial: '—',
            initial: '—',
        },
    },
    {
        id: 13,
        ipa: '[iː]',
        latinSymbol: 'î,y',
        englishApproximation: '<p>s<strong>ee</strong></p>',
        video: 'https://www.youtube.com/watch?v=7c1j7Npi5_I&t=7s',
        vowel: true,
        variants: {
            isolated: 'ی',
            final: 'ـی',
            medial: 'ـیـ',
            initial: 'یـ',
        },
    },
    {
        id: 14,
        ipa: '[ʒ]',
        latinSymbol: 'j',
        englishApproximation: '<p>s<strong>ee</strong></p>',
        video: 'https://www.youtube.com/watch?v=Q-idnJwQcbg&t=7s',
        vowel: false,
        variants: {
            isolated: 'ژ',
            final: 'ـژ',
            medial: 'ـژ',
            initial: 'ژ',
        },
    },
    {
        id: 15,
        ipa: '[k]',
        latinSymbol: 'k',
        englishApproximation: '<p>s<strong>k</strong>in</p>',
        video: 'https://www.youtube.com/watch?v=j8PnsSL2RgI&t=7s',
        vowel: false,
        variants: {
            isolated: 'ک',
            final: 'ـک',
            medial: 'ـکـ',
            initial: 'کـ',
        },
    },
    {
        id: 16,
        ipa: '[l]',
        latinSymbol: 'l',
        englishApproximation: '<p><strong>l</strong>ip</p>',
        video: 'https://www.youtube.com/watch?v=p8i2X8kFHf8&t=7s',
        vowel: false,
        variants: {
            isolated: 'ل',
            final: 'ـل',
            medial: 'ـلـ',
            initial: 'لـ',
        },
    },
    {
        id: 17,
        ipa: '[ɫ]',
        latinSymbol: '(l)',
        englishApproximation: '<p>pi<strong>ll</strong></p>',
        video: 'https://www.youtube.com/watch?v=NvmQuSGq53c&t=7s',
        vowel: false,
        variants: {
            isolated: 'ڵ',
            final: 'ـڵ',
            medial: 'ـڵـ',
            initial: '—',
        },
    },
    {
        id: 18,
        ipa: '[m]',
        latinSymbol: 'm',
        englishApproximation: '<p><strong>m</strong>oon</p>',
        video: 'https://www.youtube.com/watch?v=gJaAZo0L2PY&t=7s',
        vowel: false,
        variants: {
            isolated: 'م',
            final: 'ـم',
            medial: 'ـمـ',
            initial: 'مـ',
        },
    },
    {
        id: 19,
        ipa: '[n]',
        latinSymbol: 'n',
        englishApproximation: '<p><strong>n</strong>ap</p>',
        video: 'https://www.youtube.com/watch?v=YoZfMMEqgug&t=7s',
        vowel: false,
        variants: {
            isolated: 'ن',
            final: 'ـن',
            medial: 'ـنـ',
            initial: 'نـ',
        },
    },
    {
        id: 20,
        ipa: '[o]',
        latinSymbol: 'o',
        englishApproximation: '<p>sh<strong>o</strong>re</p>',
        video: 'https://www.youtube.com/watch?v=I4kLLlLMDmY&t=7s',
        vowel: true,
        variants: {
            isolated: 'ۆ',
            final: 'ـۆ',
            medial: 'ـۆ',
            initial: 'ۆ',
        },
    },
    {
        id: 21,
        ipa: '[p]',
        latinSymbol: 'p',
        englishApproximation: '<p>s<strong>p</strong>in</p>',
        video: 'https://www.youtube.com/watch?v=ekoUiiyjw0A&t=7s',
        vowel: false,
        variants: {
            isolated: 'پ',
            final: 'ـپ',
            medial: 'ـپـ',
            initial: 'پـ',
        },
    },
    {
        id: 22,
        ipa: '[q]',
        latinSymbol: 'q',
        englishApproximation: '<p><strong>c</strong>all (but further back in the throat</p>',
        video: 'https://www.youtube.com/watch?v=Dp3Jf14MjZU&t=7s',
        vowel: false,
        variants: {
            isolated: 'ق',
            final: 'ـق',
            medial: 'ـقـ',
            initial: 'قـ',
        },
    },
    {
        id: 23,
        ipa: '[ɾ]',
        latinSymbol: 'r',
        englishApproximation: '<p>bu<strong>tt</strong>er (American English)</p>',
        video: 'https://www.youtube.com/watch?v=8sRlIMTyHYs&t=7s',
        vowel: false,
        variants: {
            isolated: 'ر',
            final: 'ـر',
            medial: 'ـر',
            initial: '—',
        },
    },
    {
        id: 24,
        ipa: '[r]',
        latinSymbol: '(r)',
        englishApproximation: '<p>rolled r</p>',
        video: 'https://www.youtube.com/watch?v=sgMrmGTz9ms&t=7s',
        vowel: false,
        variants: {
            isolated: 'ڕ',
            final: 'ـڕ',
            medial: 'ـڕ',
            initial: 'ڕ',
        },
    },
    {
        id: 25,
        ipa: '[s]',
        latinSymbol: 's',
        englishApproximation: '<p><strong>s</strong>ip</p>',
        video: 'https://www.youtube.com/watch?v=rHTBb_2ME5g&t=7s',
        vowel: false,
        variants: {
            isolated: 'س',
            final: 'ـس',
            medial: 'ـسـ',
            initial: 'سـ',
        },
    },
    {
        id: 26,
        ipa: '[ʃ]',
        latinSymbol: 'ş',
        englishApproximation: '<p><strong>sh</strong>ip</p>',
        video: 'https://www.youtube.com/watch?v=yxFQ0Na85Gk&t=7s',
        vowel: false,
        variants: {
            isolated: 'ش',
            final: 'ـش',
            medial: 'ـشـ',
            initial: 'شـ',
        },
    },
    {
        id: 27,
        ipa: '[t]',
        latinSymbol: 't',
        englishApproximation: '<p>s<strong>t</strong>op</p>',
        video: 'https://www.youtube.com/watch?v=j04rDZX48TU&t=7s',
        vowel: false,
        variants: {
            isolated: 'ت',
            final: 'ـت',
            medial: 'ـتـ',
            initial: 'تـ',
        },
    },
    {
        id: 28,
        ipa: '[u]',
        latinSymbol: 'u,w',
        englishApproximation: '<p>p<strong>u</strong>ll</p>',
        video: 'https://www.youtube.com/watch?v=I4kLLlLMDmY&t=7s',
        vowel: true,
        variants: {
            isolated: 'و',
            final: 'ـو',
            medial: 'ـو',
            initial: 'و',
        },
    },
    {
        id: 29,
        ipa: '[uː]',
        latinSymbol: 'û',
        englishApproximation: '<p>m<strong>oo</strong>n</p>',
        video: 'https://www.youtube.com/watch?v=02xWfJ6WW20&t=7s',
        vowel: false,
        variants: {
            isolated: 'وو',
            final: 'ـوو',
            medial: 'ـوو',
            initial: '—',
        },
    },
    {
        id: 30,
        ipa: '[yː]',
        latinSymbol: '?',
        englishApproximation: '<p>somewhat like c<strong>u</strong>te</p>',
        video: '&t=7s',
        vowel: false,
        variants: {
            isolated: 'ۊ',
            final: '—',
            medial: '—',
            initial: 'ـۊ',
        },
    },
    {
        id: 31,
        ipa: '[v]',
        latinSymbol: 'v',
        englishApproximation: '<p><strong>v</strong>ase</p>',
        video: 'https://www.youtube.com/watch?v=RhNntT_H8W4&t=7s',
        vowel: false,
        variants: {
            isolated: 'ڤ',
            final: 'ـڤ',
            medial: 'ـڤـ',
            initial: 'ڤـ',
        },
    },
    {
        id: 32,
        ipa: '[x]',
        latinSymbol: 'x',
        englishApproximation: '<p>Scottish lo<strong>ch</strong></p>',
        video: 'https://www.youtube.com/watch?v=6rPwb7DcjrY&t=7s',
        vowel: false,
        variants: {
            isolated: 'خ',
            final: 'ـخ',
            medial: 'ـخـ',
            initial: 'خـ',
        },
    },
    {
        id: 33,
        ipa: '[ɣ]',
        latinSymbol: 'ẍ',
        englishApproximation:
            '<p><strong>go</strong>, but without completely blocking airflow on the <strong>g</strong></p>',
        video: 'https://www.youtube.com/watch?v=VQ-ZABkIpC86&t=7s',
        vowel: false,
        variants: {
            isolated: 'غ',
            final: 'ـغ',
            medial: 'ـغـ',
            initial: 'غـ',
        },
    },
    {
        id: 34,
        ipa: '[z]',
        latinSymbol: 'z',
        englishApproximation: '<p><strong>z</strong>ap</p>',
        video: 'https://www.youtube.com/watch?v=275ORJTIJSQ&t=7s',
        vowel: false,
        variants: {
            isolated: 'ز',
            final: 'ـز',
            medial: 'ـز',
            initial: 'ز',
        },
    },
    {
        id: 35,
        ipa: '[ʕ]',
        latinSymbol: "(')",
        englishApproximation: '3',
        video: 'https://www.youtube.com/watch?v=m2WKf_AtUlU&t=7s',
        vowel: false,
        variants: {
            isolated: 'ع',
            final: 'ـع',
            medial: 'ـعـ',
            initial: 'عـ',
        },
    },
];

export const words: Word[] = [
    {
        id: 1,
        sorani: 'ئاو',
        english: 'water',
        ipa: '',
    },
    {
        id: 2,
        sorani: 'بزن',
        english: 'goat',
        ipa: '',
    },
    {
        id: 3,
        sorani: 'جووت',
        english: 'pair',
        ipa: '',
    },
    {
        id: 4,
        sorani: 'چونکە',
        english: 'because',
        ipa: '',
    },
];
